server:
  port: 9000

security:
  user:
    password: password

zuul:
  routes:
    springbox-catalog: /catalog/**
    springbox-reviews: /reviews/**
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    springbox-recommendations: /recomendations/**

spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret

    resource:
      userInfoUri: http://localhost:9999/uaa/user


logging:
  level:
    org.springframework.security: DEBUG
